drop table if exists board CASCADE;
drop table if exists board_img_src_detail CASCADE;
drop table if exists board_video_src CASCADE;
drop table if exists category CASCADE;
drop table if exists common_attach CASCADE;
drop table if exists apple CASCADE;
drop table if exists APPDDD CASCADE;


create table board (
id integer generated by default as identity,
amount integer,
contents varchar(255),
revision_no integer,
revision_noti varchar(255),
state varchar(255),
subject varchar(255),
term varchar(255),
category_id integer,
img_src_main_id integer,
created_date timestamp,
created_id varchar(255),
del_yn char default 'N' not null,
modified_date timestamp,
modified_id varchar(255),
primary key (id)
);    
create table board_img_src_detail (
board_id integer not null,
img_src_detail_id integer not null
);
create table board_video_src (
board_id integer not null,
video_src_id integer not null
);
create table category (
id integer generated by default as identity,
name varchar(255),
description varchar(255),
sort integer,
created_date timestamp,
created_id varchar(255),
del_yn char default 'N' not null,
modified_date timestamp,
modified_id varchar(255),
primary key (id)
);
create table common_attach (
id integer generated by default as identity,
file_name varchar(255),
file_path varchar(255),
parent_id integer,
type varchar(255),
created_date timestamp,
created_id varchar(255),
del_yn char default 'N' not null,
modified_date timestamp,
modified_id varchar(255),
primary key (id)
);
alter table board_img_src_detail
add constraint UK_board_img_src_detail_1 unique (img_src_detail_id);
alter table board_video_src
add constraint UK_board_video_src_1 unique (video_src_id);
alter table board
add constraint FK_board_to_category
foreign key (category_id)
references category;

alter table board
add constraint FK_board_to_common_attach
foreign key (img_src_main_id)
references common_attach;

alter table board_img_src_detail
add constraint FK_board_img_src_detail_1
foreign key (img_src_detail_id)
references common_attach;

alter table board_img_src_detail
add constraint FK_board_img_src_detail_2
foreign key (board_id)
references board;

alter table board_video_src
add constraint FK_board_video_src_1
foreign key (video_src_id)
references common_attach;

alter table board_video_src
add constraint FK_board_video_src_2
foreign key (board_id)
references board;